controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# ✅ Configuration correcte de Nelmio API Doc
nelmio_api_doc:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui

