nelmio_api_doc:
    documentation:
        info:
            title: "Mini Plan API"
            description: "Documentation de l'API Mini Plan avec Swagger"
            version: "1.0.0"
    areas:
        path_patterns:
            - ^/api
