<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEOyUkpp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEOyUkpp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEOyUkpp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEOyUkpp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEOyUkpp\App_KernelDevDebugContainer([
    'container.build_hash' => 'EOyUkpp',
    'container.build_id' => 'b2d7f190',
    'container.build_time' => 1745508765,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEOyUkpp');
