<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Member extends \App\Entity\Member implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'date_of_birth' => [parent::class, 'date_of_birth', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'relationship' => [parent::class, 'relationship', null],
        "\0".parent::class."\0".'space' => [parent::class, 'space', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'subscriptions' => [parent::class, 'subscriptions', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'created_at' => [parent::class, 'created_at', null],
        'date_of_birth' => [parent::class, 'date_of_birth', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'relationship' => [parent::class, 'relationship', null],
        'space' => [parent::class, 'space', null],
        'status' => [parent::class, 'status', null],
        'subscriptions' => [parent::class, 'subscriptions', null],
        'updated_at' => [parent::class, 'updated_at', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
