<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Space extends \App\Entity\Space implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdBy' => [parent::class, 'createdBy', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'invitations' => [parent::class, 'invitations', null],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null],
        "\0".parent::class."\0".'members' => [parent::class, 'members', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'notifications' => [parent::class, 'notifications', null],
        "\0".parent::class."\0".'permissions' => [parent::class, 'permissions', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        "\0".parent::class."\0".'visibility' => [parent::class, 'visibility', null],
        'createdBy' => [parent::class, 'createdBy', null],
        'created_at' => [parent::class, 'created_at', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'invitations' => [parent::class, 'invitations', null],
        'logo' => [parent::class, 'logo', null],
        'members' => [parent::class, 'members', null],
        'name' => [parent::class, 'name', null],
        'notifications' => [parent::class, 'notifications', null],
        'permissions' => [parent::class, 'permissions', null],
        'status' => [parent::class, 'status', null],
        'updated_at' => [parent::class, 'updated_at', null],
        'visibility' => [parent::class, 'visibility', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
