<?php

namespace ContainerPTda6wS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M6r5JUzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M6r5JUz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M6r5JUz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
            'logger' => ['privates', 'logger', 'getLoggerService', false],
        ], [
            'entityManager' => '?',
            'validator' => '?',
            'logger' => '?',
        ]);
    }
}
