<?php

namespace ContainerPTda6wS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GDJi_RQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gDJi.rQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gDJi.rQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\SubscriptionTagRepository', 'getSubscriptionTagRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\SubscriptionTagRepository',
        ]);
    }
}
