<?php

namespace ContainerPTda6wS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllerdeleteCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HQ.7fB5.App\Controller\CategoryController::deleteCategory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HQ.7fB5.App\\Controller\\CategoryController::deleteCategory()'] = ($container->privates['.service_locator.HQ.7fB5'] ?? $container->load('get_ServiceLocator_HQ_7fB5Service'))->withContext('App\\Controller\\CategoryController::deleteCategory()', $container);
    }
}
