<?php

namespace ContainerPTda6wS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllergetAllPaymentsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.03VufjH.App\Controller\PaymentController::getAllPayments()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.03VufjH.App\\Controller\\PaymentController::getAllPayments()'] = ($container->privates['.service_locator.03VufjH'] ?? $container->load('get_ServiceLocator_03VufjHService'))->withContext('App\\Controller\\PaymentController::getAllPayments()', $container);
    }
}
