<?php

namespace ContainerPTda6wS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllercreateUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xl1aRqp.App\Controller\UserController::createUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xl1aRqp.App\\Controller\\UserController::createUser()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
            'logger' => ['privates', 'logger', 'getLoggerService', false],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'validator' => '?',
            'logger' => '?',
        ]))->withContext('App\\Controller\\UserController::createUser()', $container);
    }
}
