<?php

namespace ContainerOGRmwL2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMemberControllerupdateMemberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cDm6hfL.App\Controller\MemberController::updateMember()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cDm6hfL.App\\Controller\\MemberController::updateMember()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'memberRepository' => ['privates', 'App\\Repository\\MemberRepository', 'getMemberRepositoryService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'entityManager' => '?',
            'memberRepository' => 'App\\Repository\\MemberRepository',
            'validator' => '?',
        ]))->withContext('App\\Controller\\MemberController::updateMember()', $container);
    }
}
