<?php

namespace ContainerOGRmwL2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllergetAllNotificationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IZrDbAW.App\Controller\NotificationController::getAllNotifications()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IZrDbAW.App\\Controller\\NotificationController::getAllNotifications()'] = ($container->privates['.service_locator.IZrDbAW'] ?? $container->load('get_ServiceLocator_IZrDbAWService'))->withContext('App\\Controller\\NotificationController::getAllNotifications()', $container);
    }
}
