<?php

namespace ContainerOGRmwL2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllermarkNotificationAsReadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XTZwFOk.App\Controller\NotificationController::markNotificationAsRead()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XTZwFOk.App\\Controller\\NotificationController::markNotificationAsRead()'] = ($container->privates['.service_locator.XTZwFOk'] ?? $container->load('get_ServiceLocator_XTZwFOkService'))->withContext('App\\Controller\\NotificationController::markNotificationAsRead()', $container);
    }
}
