<?php

namespace ContainerOGRmwL2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPermissionControllerassignPermissionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M6r5JUz.App\Controller\PermissionController::assignPermission()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M6r5JUz.App\\Controller\\PermissionController::assignPermission()'] = ($container->privates['.service_locator.M6r5JUz'] ?? $container->load('get_ServiceLocator_M6r5JUzService'))->withContext('App\\Controller\\PermissionController::assignPermission()', $container);
    }
}
