<?php

namespace ContainerOGRmwL2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllercreatePaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gtQW1HD.App\Controller\PaymentController::createPayment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gtQW1HD.App\\Controller\\PaymentController::createPayment()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
            'subscriptionRepository' => ['privates', 'App\\Repository\\SubscriptionRepository', 'getSubscriptionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'validator' => '?',
            'subscriptionRepository' => 'App\\Repository\\SubscriptionRepository',
        ]))->withContext('App\\Controller\\PaymentController::createPayment()', $container);
    }
}
