<?php

namespace ContainerOGRmwL2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionTagControllergetAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gDJi.rQ.App\Controller\SubscriptionTagController::getAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gDJi.rQ.App\\Controller\\SubscriptionTagController::getAll()'] = ($container->privates['.service_locator.gDJi.rQ'] ?? $container->load('get_ServiceLocator_GDJi_RQService'))->withContext('App\\Controller\\SubscriptionTagController::getAll()', $container);
    }
}
