<?php

namespace ContainerLQC1YB2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L7r55b7Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.L7r55b7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L7r55b7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'spaceRepository' => ['privates', 'App\\Repository\\SpaceRepository', 'getSpaceRepositoryService', true],
        ], [
            'spaceRepository' => 'App\\Repository\\SpaceRepository',
        ]);
    }
}
