<?php

namespace ContainerLQC1YB2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_V4zk83HService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored.V4zk83H' shared service.
     *
     * @return \App\Repository\UsersRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AuthController::login()": the $userRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\UsersRepository".');
    }
}
