<?php

namespace ContainerLQC1YB2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerupdatePaymentService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.4RUu2Zl.App\Controller\PaymentController::updatePayment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4RUu2Zl.App\\Controller\\PaymentController::updatePayment()'] = ($container->privates['.service_locator.4RUu2Zl'] ?? $container->load('get_ServiceLocator_4RUu2ZlService'))->withContext('App\\Controller\\PaymentController::updatePayment()', $container);
    }
}
