<?php

namespace ContainerLQC1YB2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpaceControllerarchiveSpaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.5DPVkPI.App\Controller\SpaceController::archiveSpace()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5DPVkPI.App\\Controller\\SpaceController::archiveSpace()'] = ($container->privates['.service_locator.5DPVkPI'] ?? $container->load('get_ServiceLocator_5DPVkPIService'))->withContext('App\\Controller\\SpaceController::archiveSpace()', $container);
    }
}
