<?php

namespace ContainerLQC1YB2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpaceControllergetSpaceByIdService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.L7r55b7.App\Controller\SpaceController::getSpaceById()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L7r55b7.App\\Controller\\SpaceController::getSpaceById()'] = ($container->privates['.service_locator.L7r55b7'] ?? $container->load('get_ServiceLocator_L7r55b7Service'))->withContext('App\\Controller\\SpaceController::getSpaceById()', $container);
    }
}
