<?php

namespace ContainerI4qD5Wk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllerupdateCategoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.HQ.7fB5.App\Controller\CategoryController::updateCategory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HQ.7fB5.App\\Controller\\CategoryController::updateCategory()'] = ($container->privates['.service_locator.HQ.7fB5'] ?? $container->load('get_ServiceLocator_HQ_7fB5Service'))->withContext('App\\Controller\\CategoryController::updateCategory()', $container);
    }
}
