<?php

namespace ContainerI4qD5Wk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMemberControllergetAllMembersService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Zurzp9s.App\Controller\MemberController::getAllMembers()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zurzp9s.App\\Controller\\MemberController::getAllMembers()'] = ($container->privates['.service_locator.Zurzp9s'] ?? $container->load('get_ServiceLocator_Zurzp9sService'))->withContext('App\\Controller\\MemberController::getAllMembers()', $container);
    }
}
