<?php

namespace ContainerI4qD5Wk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllergetPaymentByIdService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.03VufjH.App\Controller\PaymentController::getPaymentById()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.03VufjH.App\\Controller\\PaymentController::getPaymentById()'] = ($container->privates['.service_locator.03VufjH'] ?? $container->load('get_ServiceLocator_03VufjHService'))->withContext('App\\Controller\\PaymentController::getPaymentById()', $container);
    }
}
