<?php

namespace ContainerI4qD5Wk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllergetAllServicesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator..wKp6bH.App\Controller\ServiceController::getAllServices()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..wKp6bH.App\\Controller\\ServiceController::getAllServices()'] = ($container->privates['.service_locator..wKp6bH'] ?? $container->load('get_ServiceLocator__WKp6bHService'))->withContext('App\\Controller\\ServiceController::getAllServices()', $container);
    }
}
