<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI4qD5Wk\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI4qD5Wk/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerI4qD5Wk.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerI4qD5Wk\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerI4qD5Wk\App_KernelTestDebugContainer([
    'container.build_hash' => 'I4qD5Wk',
    'container.build_id' => '2e7b3087',
    'container.build_time' => 1742892810,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI4qD5Wk');
